---
title: Exception / Throws
tags: [JAVA, Exception, Throws]
categories:
  - JAVA
date: 2022-01-16
toc : true
---

## Exception
- 예외 처리, try... catch ...finally
    - try : 기본적으로 실행되는 코드
    - catch : try에서 예외가 발생됬을 때 실행되는 코드
    - finally : 오류가 발생하든 안하든 무조건 실행되는 코드
- try블록에서 여러종류의 Exception이 발생한다면 catch라는 블록 여러개 가능
- Exception클래스들은 모두 Exception클래스를 상속받으므로, 예외클래스에 Exception을 두게 되면 하나의 catch블록에서 모든 오류 처리 가능

```java 
  public class ExceptionExam {
        public static void main(String[] args) {
            int i = 10;
            int j = 0;
            try{
                int k = i / j;
                System.out.println(k);
            }catch(ArithmeticException e){
                System.out.println("0으로 나눌 수 없습니다. : " + e.toString());
            }finally {
                System.out.println("오류가 발생하든 안하든 무조건 실행되는 블록입니다.");
            }
        }
    }
```

## Throws 
- 예외가 발생했을 때, 예외를 호출한 쪽에서 처리하도록 던져줌

``` java
    package javaStudy;
    public class ExceptionExam2 {

        public static void main(String[] args) {
            int i = 10;
            int j = 0;
            try{
                int k = divide(i, j);
                System.out.println(k);
            } catch(ArithmeticException e){
                System.out.println("0으로 나눌수 없습니다.");
            }

        }

        public static int divide(int i, int j) throws ArithmeticException{
            int k = i / j;
            return k;
        }

    }
```